### Test health endpoint
GET http://127.0.0.1:5000/health

### Test root endpoint
GET http://127.0.0.1:5000/

### Test 404 error
GET http://127.0.0.1:5000/notfound

### Test 405 error
POST http://127.0.0.1:5000/health