# Generated by Django 5.2.8 on 2025-12-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='api_calls_limit',
            field=models.IntegerField(default=10000, help_text='API calls per month'),
        ),
        migrations.AddField(
            model_name='product',
            name='data_limit_mb',
            field=models.IntegerField(default=100, help_text='Data download limit in MB'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_1_month',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_1_year',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_2_months',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
