# Generated by Django 5.2.8 on 2025-12-04 10:19

import datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_price_product_api_calls_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionalert',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='product',
            name='api_calls_limit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_limit_mb',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_1_month',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_1_year',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_2_months',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='api_calls_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='data_downloaded_mb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='data_limit_mb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 4, 10, 19, 30, 15935, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionusage',
            name='avg_response_time_ms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionusage',
            name='data_downloaded_mb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionusage',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='core_subscr_user_id_d435c1_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at'], name='core_subscr_expires_859060_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusage',
            index=models.Index(fields=['subscription', 'date'], name='core_subscr_subscri_9bcb44_idx'),
        ),
        migrations.DeleteModel(
            name='SubscriptionAlert',
        ),
    ]
