# Generated by Django 5.2.8 on 2025-12-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_1_month',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_1_year',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_2_months',
        ),
        migrations.AddField(
            model_name='product',
            name='price_10_minutes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='10 Minutes Plan'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_1_week',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='1 Week Plan'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_2_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='2 Hours Plan'),
        ),
    ]
